"""Seeds the disease + treatment reference tables.

IMPORTANT (CLAUDE.md section 14): these recommendations are NOT generated by an
AI model. They are cultural / integrated-management practices that are standard
in public agricultural extension guidance, deliberately written WITHOUT specific
pesticide products, dosages or application rates — those are region-, crop- and
regulation-specific and must come from a local agricultural officer.

Every entry names the kind of source it reflects. Before this project is used
with real farmers, each row should be checked against your state agricultural
university / extension service and the `source` field updated to the exact
document.
"""

from sqlalchemy.orm import Session

from app.database.session import Base, SessionLocal, engine
from app.models import Disease, Treatment

# Shown whenever we have no verified treatment for a predicted disease.
NO_TREATMENT_TEXT = {
    "en": (
        "No verified recommendation is currently available for this result. "
        "Please consult a qualified agricultural expert or your local "
        "agricultural extension officer."
    ),
    "ta": (
        "இந்த முடிவுக்கு தற்போது சரிபார்க்கப்பட்ட பரிந்துரை எதுவும் இல்லை. "
        "தயவுசெய்து தகுதிவாய்ந்த வேளாண் நிபுணரையோ உங்கள் பகுதி வேளாண் "
        "விரிவாக்க அலுவலரையோ அணுகவும்."
    ),
}

EXTENSION_SOURCE = (
    "General integrated disease management practice from public agricultural "
    "extension guidance. Verify with your local agricultural officer before "
    "applying any chemical control."
)

# (crop, disease_key, display name, description, {lang: recommendation})
SEED_DATA = [
    (
        "tomato",
        "early_blight",
        "Tomato Early Blight",
        "A fungal leaf spot disease showing dark spots with concentric rings, "
        "usually starting on older, lower leaves.",
        {
            "en": (
                "Remove and destroy affected lower leaves and any crop debris. "
                "Avoid overhead watering — water at the base so leaves stay dry. "
                "Space plants for good air movement and use stakes to keep "
                "foliage off the soil. Mulch to stop soil splashing onto leaves. "
                "Rotate away from tomato, potato and brinjal for at least two "
                "seasons. If the spread is severe, ask your agricultural officer "
                "which fungicide is approved locally and at what rate."
            ),
            "ta": (
                "பாதிக்கப்பட்ட கீழ் இலைகளையும் பயிர்க் கழிவுகளையும் அகற்றி "
                "அழிக்கவும். மேலிருந்து நீர் தெளிப்பதைத் தவிர்த்து, செடியின் "
                "அடிப்பகுதியில் மட்டும் நீர் பாய்ச்சவும். செடிகளுக்கு இடையே "
                "போதிய இடைவெளி விட்டு காற்றோட்டம் இருக்கச் செய்யவும்; "
                "கழிகள் கட்டி இலைகள் மண்ணில் படாமல் பார்த்துக்கொள்ளவும். "
                "மண் இலைகளில் தெறிக்காமல் இருக்க மூடாக்கு இடவும். "
                "தக்காளி, உருளைக்கிழங்கு, கத்திரி பயிர்களைத் தவிர்த்து "
                "குறைந்தது இரண்டு பருவங்களுக்கு பயிர் சுழற்சி செய்யவும். "
                "நோய் அதிகமாக பரவினால், எந்த பூஞ்சைக் கொல்லியை எவ்வளவு "
                "அளவில் பயன்படுத்தலாம் என்பதை உங்கள் வேளாண் அலுவலரிடம் கேளுங்கள்."
            ),
        },
    ),
    (
        "tomato",
        "late_blight",
        "Tomato Late Blight",
        "A fast-moving disease causing large water-soaked greasy patches on "
        "leaves and stems, worst in cool, wet, humid weather.",
        {
            "en": (
                "Act quickly — this disease spreads fast in cool wet weather. "
                "Pull out and destroy badly affected plants; do not compost them. "
                "Keep leaves dry, improve drainage and air flow, and avoid "
                "working among wet plants. Do not plant tomato next to potato. "
                "Because late blight can destroy a field within days, contact "
                "your agricultural extension officer immediately for the "
                "currently approved control measure in your area."
            ),
            "ta": (
                "உடனடியாக நடவடிக்கை எடுக்கவும் — குளிர்ந்த ஈரமான காலநிலையில் "
                "இந்நோய் வேகமாகப் பரவும். மோசமாகப் பாதிக்கப்பட்ட செடிகளை "
                "வேரோடு அகற்றி அழிக்கவும்; அவற்றை உரக்குழியில் போடவேண்டாம். "
                "இலைகளை உலர்வாக வைத்திருக்கவும், நீர் வடிதலையும் காற்றோட்டத்தையும் "
                "மேம்படுத்தவும், ஈரமான செடிகளுக்கு இடையே வேலை செய்வதைத் தவிர்க்கவும். "
                "தக்காளியை உருளைக்கிழங்கிற்கு அருகில் நடவேண்டாம். "
                "இந்நோய் சில நாட்களிலேயே வயலை அழிக்கக்கூடியது என்பதால், "
                "உங்கள் பகுதியில் தற்போது அனுமதிக்கப்பட்ட கட்டுப்பாட்டு "
                "முறைக்காக வேளாண் விரிவாக்க அலுவலரை உடனே தொடர்பு கொள்ளவும்."
            ),
        },
    ),
    (
        "tomato",
        "leaf_mold",
        "Tomato Leaf Mold",
        "Pale yellow patches on the upper leaf surface with olive-green to "
        "brown velvety mould underneath. Mainly a problem in humid, enclosed "
        "conditions such as polyhouses.",
        {
            "en": (
                "Reduce humidity: increase ventilation, widen plant spacing and "
                "prune lower leaves so air can move through the canopy. Water at "
                "the base, early in the day, so foliage dries quickly. Remove "
                "affected leaves and clear all crop residue after harvest. Where "
                "available, grow resistant varieties. Consult your agricultural "
                "officer before using any chemical control."
            ),
            "ta": (
                "ஈரப்பதத்தைக் குறைக்கவும்: காற்றோட்டத்தை அதிகரிக்கவும், "
                "செடிகளுக்கு இடையே இடைவெளியை அதிகரிக்கவும், கீழ் இலைகளைக் "
                "கத்தரித்து காற்று செல்ல வழி செய்யவும். காலையில் அடிப்பகுதியில் "
                "நீர் பாய்ச்சி இலைகள் விரைவில் உலரச் செய்யவும். பாதிக்கப்பட்ட "
                "இலைகளை அகற்றி, அறுவடைக்குப் பிறகு பயிர்க் கழிவுகளை முழுவதுமாக "
                "நீக்கவும். கிடைக்கும் இடங்களில் நோய் எதிர்ப்புத் திறன் கொண்ட "
                "ரகங்களை பயிரிடவும். வேதிப் பொருள் பயன்படுத்தும் முன் வேளாண் "
                "அலுவலரை அணுகவும்."
            ),
        },
    ),
    (
        "potato",
        "early_blight",
        "Potato Early Blight",
        "Dark brown spots with concentric rings on older leaves, often when "
        "plants are stressed or short of nitrogen.",
        {
            "en": (
                "Keep plants well nourished and evenly watered — stressed crops "
                "are hit hardest. Remove affected lower leaves and destroy crop "
                "debris after harvest. Practise crop rotation with non-solanaceous "
                "crops. Earth up plants well and avoid overhead irrigation. Ask "
                "your agricultural officer about approved fungicides if the "
                "disease keeps spreading."
            ),
            "ta": (
                "செடிகளுக்கு போதிய ஊட்டச்சத்தும் சீரான நீரும் அளிக்கவும் — "
                "வலுவிழந்த பயிர்களே அதிகம் பாதிக்கப்படும். பாதிக்கப்பட்ட கீழ் "
                "இலைகளை அகற்றி, அறுவடைக்குப் பின் பயிர்க் கழிவுகளை அழிக்கவும். "
                "சோலனேசி அல்லாத பயிர்களுடன் பயிர் சுழற்சி செய்யவும். செடிகளுக்கு "
                "நன்கு மண் அணைத்து, மேலிருந்து நீர் பாய்ச்சுவதைத் தவிர்க்கவும். "
                "நோய் தொடர்ந்து பரவினால் அனுமதிக்கப்பட்ட பூஞ்சைக் கொல்லிகள் "
                "குறித்து வேளாண் அலுவலரிடம் கேளுங்கள்."
            ),
        },
    ),
    (
        "potato",
        "late_blight",
        "Potato Late Blight",
        "Water-soaked dark lesions on leaves with white mould at the edges in "
        "humid weather; can rot tubers. Spreads extremely fast.",
        {
            "en": (
                "This is a serious, fast-spreading disease — report it early. "
                "Destroy affected plants and any volunteer potatoes. Use only "
                "certified healthy seed tubers. Earth up ridges well so spores "
                "cannot reach the tubers, and harvest only in dry conditions. "
                "Contact your agricultural extension officer immediately for the "
                "control measure approved in your district."
            ),
            "ta": (
                "இது வேகமாகப் பரவும் தீவிரமான நோய் — ஆரம்பத்திலேயே தெரிவிக்கவும். "
                "பாதிக்கப்பட்ட செடிகளையும் தானாக முளைத்த உருளைக்கிழங்கு "
                "செடிகளையும் அழிக்கவும். சான்றளிக்கப்பட்ட ஆரோக்கியமான விதைக் "
                "கிழங்குகளை மட்டுமே பயன்படுத்தவும். வித்திகளை கிழங்கு வரை "
                "சேராதவாறு நன்கு மண் அணைக்கவும்; உலர்ந்த சூழலில் மட்டும் "
                "அறுவடை செய்யவும். உங்கள் மாவட்டத்தில் அனுமதிக்கப்பட்ட "
                "கட்டுப்பாட்டு முறைக்காக வேளாண் விரிவாக்க அலுவலரை உடனே "
                "தொடர்பு கொள்ளவும்."
            ),
        },
    ),
    (
        "corn",
        "common_rust",
        "Maize Common Rust",
        "Small reddish-brown powdery pustules scattered on both leaf surfaces.",
        {
            "en": (
                "Grow resistant hybrids where they are available — this is the "
                "most effective and cheapest control. Avoid very late or very "
                "staggered planting, which keeps a green bridge for the fungus. "
                "Remove volunteer maize plants. Light infections late in the "
                "season usually do not need spraying; if it appears early and "
                "spreads, consult your agricultural officer."
            ),
            "ta": (
                "கிடைக்கும் இடங்களில் நோய் எதிர்ப்புத் திறன் கொண்ட ஒட்டு "
                "ரகங்களை பயிரிடவும் — இதுவே மிகச் சிறந்த, மலிவான கட்டுப்பாடு. "
                "மிகவும் தாமதமான அல்லது பல கட்டங்களாகப் பிரிந்த விதைப்பைத் "
                "தவிர்க்கவும். தானாக முளைத்த சோள செடிகளை அகற்றவும். பருவ "
                "இறுதியில் ஏற்படும் லேசான தாக்குதலுக்கு மருந்து தெளிக்க "
                "தேவையில்லை; ஆரம்பத்திலேயே தோன்றி பரவினால் வேளாண் அலுவலரை "
                "அணுகவும்."
            ),
        },
    ),
    (
        "corn",
        "northern_leaf_blight",
        "Maize Northern Leaf Blight",
        "Long cigar-shaped grey-green lesions running along the leaf.",
        {
            "en": (
                "Choose resistant hybrids where available. Rotate maize with a "
                "non-host crop and plough in or remove infected residue, since "
                "the fungus survives on old stubble. Avoid dense planting so the "
                "canopy dries faster. Ask your agricultural officer about "
                "approved fungicides if lesions appear before tasselling."
            ),
            "ta": (
                "கிடைக்கும் இடங்களில் நோய் எதிர்ப்பு ரகங்களைத் தேர்வு செய்யவும். "
                "சோளத்தை வேறு பயிருடன் சுழற்சி செய்யவும்; பூஞ்சை பழைய "
                "தாள்களில் உயிர் வாழ்வதால் பாதிக்கப்பட்ட கழிவுகளை உழுது "
                "மண்ணில் சேர்க்கவும் அல்லது அகற்றவும். அடர்த்தியான விதைப்பைத் "
                "தவிர்த்து இலைப்பரப்பு விரைவில் உலரச் செய்யவும். கதிர் வருவதற்கு "
                "முன்பே புள்ளிகள் தோன்றினால் அனுமதிக்கப்பட்ட பூஞ்சைக் "
                "கொல்லிகள் குறித்து வேளாண் அலுவலரிடம் கேளுங்கள்."
            ),
        },
    ),
    (
        "rice",
        "leaf_blast",
        "Rice Leaf Blast",
        "Spindle-shaped lesions with grey centres and brown margins on leaves.",
        {
            "en": (
                "Avoid excessive nitrogen — over-fertilised crops are far more "
                "susceptible. Split nitrogen application instead of applying it "
                "all at once. Keep a stable water level in the field and avoid "
                "drought stress. Use resistant varieties and clean, treated seed, "
                "and destroy infected stubble. Consult your agricultural officer "
                "for approved fungicide recommendations if blast appears at the "
                "seedling or neck stage."
            ),
            "ta": (
                "அதிகப்படியான தழைச்சத்தை (நைட்ரஜன்) தவிர்க்கவும் — அதிக உரம் "
                "இட்ட பயிர்கள் மிக எளிதில் பாதிக்கப்படும். நைட்ரஜனை ஒரே "
                "முறையில் இடாமல் பல தவணைகளாகப் பிரித்து இடவும். வயலில் நீர் "
                "மட்டத்தை சீராக வைத்திருந்து வறட்சி அழுத்தத்தைத் தவிர்க்கவும். "
                "நோய் எதிர்ப்பு ரகங்களையும் விதை நேர்த்தி செய்யப்பட்ட சுத்தமான "
                "விதைகளையும் பயன்படுத்தவும்; பாதிக்கப்பட்ட தாள்களை அழிக்கவும். "
                "நாற்று அல்லது கழுத்து நிலையில் நோய் தோன்றினால் அனுமதிக்கப்பட்ட "
                "பூஞ்சைக் கொல்லி பரிந்துரைக்காக வேளாண் அலுவலரை அணுகவும்."
            ),
        },
    ),
    (
        "rice",
        "bacterial_leaf_blight",
        "Rice Bacterial Leaf Blight",
        "Yellow to white wavy lesions starting at the leaf tips and edges, "
        "spreading downward.",
        {
            "en": (
                "This is a bacterial disease — fungicides do not control it. "
                "Use resistant varieties and certified seed. Avoid excess "
                "nitrogen and avoid injuring seedlings during transplanting, as "
                "wounds let the bacteria in. Drain the field periodically where "
                "possible and remove weed hosts and infected stubble. Report "
                "outbreaks to your agricultural extension officer."
            ),
            "ta": (
                "இது ஒரு பாக்டீரியா நோய் — பூஞ்சைக் கொல்லிகள் இதைக் "
                "கட்டுப்படுத்தாது. நோய் எதிர்ப்பு ரகங்களையும் சான்றளிக்கப்பட்ட "
                "விதைகளையும் பயன்படுத்தவும். அதிக நைட்ரஜனைத் தவிர்க்கவும்; "
                "நடவின்போது நாற்றுகளுக்குக் காயம் ஏற்படாமல் பார்த்துக்கொள்ளவும், "
                "ஏனெனில் காயங்கள் வழியாகவே பாக்டீரியா உள்ளே நுழையும். முடிந்தால் "
                "அவ்வப்போது வயலில் நீரை வடித்துவிடவும்; களைகளையும் பாதிக்கப்பட்ட "
                "தாள்களையும் அகற்றவும். நோய் பரவலை வேளாண் விரிவாக்க அலுவலரிடம் "
                "தெரிவிக்கவும்."
            ),
        },
    ),
]

# "healthy" is a valid model output and needs its own message per crop.
HEALTHY_TEXT = {
    "en": (
        "No disease was detected in this image. Keep monitoring the crop "
        "regularly, especially after rain or humid weather, and report any new "
        "spots or discolouration early."
    ),
    "ta": (
        "இந்தப் படத்தில் நோய் எதுவும் கண்டறியப்படவில்லை. குறிப்பாக மழை அல்லது "
        "ஈரமான காலநிலைக்குப் பிறகு, பயிரைத் தொடர்ந்து கண்காணிக்கவும்; புதிய "
        "புள்ளிகள் அல்லது நிற மாற்றம் தெரிந்தால் உடனே தெரிவிக்கவும்."
    ),
}

HEALTHY_CROPS = ["tomato", "potato", "corn", "rice"]


def seed(db: Session) -> None:
    """Insert reference data. Safe to run repeatedly — existing rows are kept."""
    entries = list(SEED_DATA)
    for crop in HEALTHY_CROPS:
        entries.append(
            (
                crop,
                "healthy",
                f"Healthy {crop.capitalize()}",
                "No disease symptoms detected.",
                HEALTHY_TEXT,
            )
        )

    for crop, key, name, description, recommendations in entries:
        disease = (
            db.query(Disease).filter_by(key=key, crop=crop).one_or_none()
        )
        if disease is None:
            disease = Disease(key=key, crop=crop, name=name, description=description)
            db.add(disease)
            db.flush()  # assign an id so treatments can reference it

        for language, text in recommendations.items():
            exists = (
                db.query(Treatment)
                .filter_by(disease_id=disease.id, language=language)
                .one_or_none()
            )
            if exists is None:
                db.add(
                    Treatment(
                        disease_id=disease.id,
                        language=language,
                        recommendation=text,
                        source=EXTENSION_SOURCE,
                    )
                )

    db.commit()


def main() -> None:
    """Entry point: `python -m app.database.seed`"""
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        seed(db)
        print(
            f"Seeded {db.query(Disease).count()} diseases and "
            f"{db.query(Treatment).count()} treatments."
        )
    finally:
        db.close()


if __name__ == "__main__":
    main()
