"""Structured, verified crop-disease reference content (English + Tamil).

IMPORTANT (CLAUDE.md section 14): none of this text is generated by an AI model.
It is standard integrated-disease-management guidance, written deliberately
WITHOUT specific pesticide products, dosages or application rates — those are
region-, crop- and regulation-specific and must come from a local agricultural
officer.

Each disease is broken into the parts a farmer actually needs, in this order:
    symptoms          what to look for, to confirm the AI's guess
    cause             the conditions that let it take hold
    severity          low | moderate | high — how urgently to act
    immediate_actions what to do today
    prevention        how to stop it coming back next season
    expert_note       when a human expert is genuinely required

Before real-world use, verify every entry against your state agricultural
university or extension service and update `source` to cite the exact document.
"""

SEVERITY_LOW = "low"
SEVERITY_MODERATE = "moderate"
SEVERITY_HIGH = "high"
SEVERITY_NONE = "none"

EXTENSION_SOURCE = (
    "General integrated disease management practice from public agricultural "
    "extension guidance. Verify with your local agricultural officer before "
    "applying any chemical control."
)

# key -> {crop, name, severity, en:{...}, ta:{...}}
DISEASES = {
    ("tomato", "early_blight"): {
        "name": "Tomato Early Blight",
        "severity": SEVERITY_MODERATE,
        "en": {
            "summary": "A common fungal leaf spot that works its way up from the oldest leaves.",
            "symptoms": (
                "Dark brown spots with concentric rings, like a target, usually starting "
                "on the lowest and oldest leaves. A yellow halo often surrounds each spot. "
                "Badly affected leaves turn yellow, dry up and drop, exposing the fruit to "
                "sunscald."
            ),
            "cause": (
                "The fungus survives on last season's crop debris and in the soil, then "
                "splashes up onto the lower leaves during rain or overhead watering. Warm, "
                "humid weather and plants short of nitrogen are hit hardest."
            ),
            "immediate_actions": [
                "Remove the affected lower leaves and destroy them — do not compost them.",
                "Stop watering from overhead; water at the base of the plant so leaves stay dry.",
                "Water early in the day so any wet foliage dries before nightfall.",
                "Spread mulch around the base to stop soil splashing onto the leaves.",
                "Stake or cage the plants so no foliage touches the soil.",
            ],
            "prevention": [
                "Rotate away from tomato, potato and brinjal for at least two seasons.",
                "Space plants further apart so air moves freely between them.",
                "Keep the crop well fed — nitrogen-starved plants are far more susceptible.",
                "Clear and destroy all crop debris after harvest.",
                "Use certified disease-free seed and resistant varieties where available.",
            ],
            "expert_note": (
                "If the spots keep spreading upward after these steps, ask your agricultural "
                "officer which fungicide is approved in your area and at what rate. Do not "
                "guess a dosage."
            ),
        },
        "ta": {
            "summary": "பழைய இலைகளிலிருந்து மேல்நோக்கிப் பரவும் பொதுவான பூஞ்சை இலைப்புள்ளி நோய்.",
            "symptoms": (
                "இலக்கு வட்டங்கள் போல ஒன்றுக்குள் ஒன்றாக வளையங்களைக் கொண்ட அடர் "
                "பழுப்புப் புள்ளிகள், பொதுவாக மிகக் கீழே உள்ள பழைய இலைகளில் தொடங்கும். "
                "ஒவ்வொரு புள்ளியையும் சுற்றி மஞ்சள் வளையம் இருக்கும். மோசமாகப் "
                "பாதிக்கப்பட்ட இலைகள் மஞ்சளாகி, உலர்ந்து உதிர்ந்து, காய்கள் "
                "வெயிலில் கருகும் அபாயம் ஏற்படும்."
            ),
            "cause": (
                "இப்பூஞ்சை சென்ற பருவப் பயிர்க் கழிவுகளிலும் மண்ணிலும் உயிர் வாழ்ந்து, "
                "மழை அல்லது மேலிருந்து நீர் பாய்ச்சும்போது கீழ் இலைகளில் தெறிக்கிறது. "
                "வெப்பமான ஈரமான காலநிலையிலும், தழைச்சத்து குறைவான செடிகளிலும் "
                "நோய் அதிகம் பாதிக்கும்."
            ),
            "immediate_actions": [
                "பாதிக்கப்பட்ட கீழ் இலைகளை அகற்றி அழிக்கவும் — உரக்குழியில் போடவேண்டாம்.",
                "மேலிருந்து நீர் பாய்ச்சுவதை நிறுத்தி, செடியின் அடிப்பகுதியில் மட்டும் நீர் விடவும்.",
                "காலையில் நீர் பாய்ச்சவும், இதனால் இரவுக்கு முன் இலைகள் உலர்ந்துவிடும்.",
                "மண் இலைகளில் தெறிக்காமல் இருக்க அடிப்பகுதியில் மூடாக்கு இடவும்.",
                "இலைகள் மண்ணில் படாதவாறு செடிகளுக்குக் கழி கட்டி நிறுத்தவும்.",
            ],
            "prevention": [
                "தக்காளி, உருளைக்கிழங்கு, கத்தரி ஆகியவற்றைத் தவிர்த்து குறைந்தது இரண்டு பருவங்கள் பயிர் சுழற்சி செய்யவும்.",
                "செடிகளுக்கு இடையே அதிக இடைவெளி விட்டு காற்றோட்டத்தை அதிகரிக்கவும்.",
                "பயிருக்குப் போதிய ஊட்டச்சத்து அளிக்கவும் — தழைச்சத்து குறைவான செடிகள் எளிதில் பாதிக்கப்படும்.",
                "அறுவடைக்குப் பிறகு அனைத்துப் பயிர்க் கழிவுகளையும் அகற்றி அழிக்கவும்.",
                "சான்றளிக்கப்பட்ட நோயற்ற விதைகளையும், கிடைத்தால் நோய் எதிர்ப்பு ரகங்களையும் பயன்படுத்தவும்.",
            ],
            "expert_note": (
                "இந்த நடவடிக்கைகளுக்குப் பிறகும் புள்ளிகள் மேல்நோக்கிப் பரவினால், "
                "உங்கள் பகுதியில் அனுமதிக்கப்பட்ட பூஞ்சைக் கொல்லி எது, எவ்வளவு அளவு "
                "என்பதை வேளாண் அலுவலரிடம் கேளுங்கள். அளவை ஊகிக்க வேண்டாம்."
            ),
        },
    },
    ("tomato", "late_blight"): {
        "name": "Tomato Late Blight",
        "severity": SEVERITY_HIGH,
        "en": {
            "summary": "A fast-moving, destructive disease that can kill a whole field within days.",
            "symptoms": (
                "Large, irregular water-soaked patches on leaves that quickly turn brown and "
                "greasy-looking, often starting at the leaf tips or edges. In humid weather a "
                "fine white mould appears on the underside. Stems develop dark brown lesions, "
                "and fruit shows firm, greasy brown blotches."
            ),
            "cause": (
                "Caused by Phytophthora infestans, which thrives in cool, wet, humid weather. "
                "Spores travel long distances on wind and rain, so it can arrive from a "
                "neighbouring field. It also survives on infected potato tubers."
            ),
            "immediate_actions": [
                "Act today — this disease can destroy a field within days.",
                "Pull out and destroy badly affected plants completely. Do not compost them.",
                "Remove infected fruit and any volunteer potato plants nearby.",
                "Stop overhead watering entirely and improve drainage.",
                "Do not work among the plants while they are wet — you will spread the spores.",
                "Warn neighbouring farmers, since spores travel on the wind.",
            ],
            "prevention": [
                "Never plant tomato next to or after potato.",
                "Use certified disease-free seed and resistant varieties.",
                "Plant with wide spacing on well-drained land with good air movement.",
                "Destroy all crop residue and leftover tubers after harvest.",
                "Watch the crop closely during cool, wet spells — that is when it strikes.",
            ],
            "expert_note": (
                "Contact your agricultural extension officer immediately. Late blight usually "
                "needs a protective spray programme to be stopped, and only they can tell you "
                "which product is currently approved in your district and at what rate."
            ),
        },
        "ta": {
            "summary": "சில நாட்களிலேயே வயல் முழுவதையும் அழிக்கக்கூடிய, வேகமாகப் பரவும் தீவிர நோய்.",
            "symptoms": (
                "இலைகளில் பெரிய, ஒழுங்கற்ற, நீரூறிய திட்டுகள் தோன்றி விரைவில் பழுப்பாகி "
                "எண்ணெய் பூசியது போலத் தெரியும்; பொதுவாக இலை நுனி அல்லது விளிம்பில் "
                "தொடங்கும். ஈரமான காலநிலையில் இலையின் அடிப்புறத்தில் மெல்லிய வெண்மையான "
                "பூஞ்சை காணப்படும். தண்டுகளில் அடர் பழுப்புப் புண்கள், காய்களில் "
                "கெட்டியான எண்ணெய்த்தன்மையுள்ள பழுப்புத் திட்டுகள் தோன்றும்."
            ),
            "cause": (
                "பைட்டோப்தோரா இன்ஃபெஸ்டான்ஸ் என்ற நோய்க்கிருமியால் ஏற்படுகிறது; "
                "குளிர்ந்த, ஈரமான, மப்பான காலநிலையில் வேகமாகப் பெருகும். வித்திகள் "
                "காற்றிலும் மழையிலும் வெகுதூரம் பயணிப்பதால் அருகிலுள்ள வயலிலிருந்தே "
                "வரலாம். பாதிக்கப்பட்ட உருளைக்கிழங்கிலும் உயிர் வாழும்."
            ),
            "immediate_actions": [
                "இன்றே நடவடிக்கை எடுக்கவும் — இந்நோய் சில நாட்களில் வயலை அழிக்கும்.",
                "மோசமாகப் பாதிக்கப்பட்ட செடிகளை முழுவதுமாக அகற்றி அழிக்கவும். உரக்குழியில் போடவேண்டாம்.",
                "பாதிக்கப்பட்ட காய்களையும், அருகில் தானாக முளைத்த உருளைக்கிழங்குச் செடிகளையும் அகற்றவும்.",
                "மேலிருந்து நீர் பாய்ச்சுவதை முற்றிலும் நிறுத்தி, நீர் வடிதலை மேம்படுத்தவும்.",
                "செடிகள் ஈரமாக இருக்கும்போது அவற்றுக்கு இடையே வேலை செய்யவேண்டாம் — வித்திகள் பரவும்.",
                "வித்திகள் காற்றில் பயணிப்பதால் அருகிலுள்ள விவசாயிகளை எச்சரிக்கவும்.",
            ],
            "prevention": [
                "தக்காளியை உருளைக்கிழங்கிற்கு அருகிலோ அதற்குப் பின்போ ஒருபோதும் நடவேண்டாம்.",
                "சான்றளிக்கப்பட்ட நோயற்ற விதைகளையும் நோய் எதிர்ப்பு ரகங்களையும் பயன்படுத்தவும்.",
                "நல்ல நீர் வடிதலும் காற்றோட்டமும் உள்ள நிலத்தில் அதிக இடைவெளியில் நடவும்.",
                "அறுவடைக்குப் பிறகு அனைத்துப் பயிர்க் கழிவுகளையும் மீதமுள்ள கிழங்குகளையும் அழிக்கவும்.",
                "குளிர்ந்த ஈரமான காலங்களில் பயிரை உன்னிப்பாகக் கண்காணிக்கவும் — அப்போதுதான் இது தாக்கும்.",
            ],
            "expert_note": (
                "உடனடியாக வேளாண் விரிவாக்க அலுவலரைத் தொடர்பு கொள்ளவும். இந்நோயைத் "
                "தடுக்க பொதுவாகப் பாதுகாப்பு மருந்து தெளிப்பு தேவைப்படும்; உங்கள் "
                "மாவட்டத்தில் தற்போது அனுமதிக்கப்பட்ட மருந்து எது, எவ்வளவு அளவு "
                "என்பதை அவர்களால் மட்டுமே சொல்ல முடியும்."
            ),
        },
    },
    ("tomato", "leaf_mold"): {
        "name": "Tomato Leaf Mould",
        "severity": SEVERITY_MODERATE,
        "en": {
            "summary": "A humidity-driven disease, mostly a problem in polyhouses and crowded plantings.",
            "symptoms": (
                "Pale green to yellow patches on the upper leaf surface, with an olive-green "
                "to greyish-brown velvety mould directly underneath. Older leaves go first. "
                "Severely affected leaves curl, wither and drop."
            ),
            "cause": (
                "Thrives above about 85% humidity with poor air movement, which is why it is "
                "worst in polyhouses, dense plantings and during long humid spells."
            ),
            "immediate_actions": [
                "Increase ventilation — open the polyhouse sides, or thin the crowded plants.",
                "Prune the lower leaves so air can move through the canopy.",
                "Remove and destroy affected leaves.",
                "Water at the base early in the day so foliage dries quickly.",
            ],
            "prevention": [
                "Grow resistant varieties where they are available.",
                "Plant at a wider spacing than usual if humidity is a known problem.",
                "Keep humidity down with ventilation rather than relying on sprays.",
                "Clear all crop residue after harvest — the fungus overwinters on it.",
            ],
            "expert_note": (
                "If ventilation and pruning do not slow it down, consult your agricultural "
                "officer before using any chemical control."
            ),
        },
        "ta": {
            "summary": "ஈரப்பதத்தால் ஏற்படும் நோய்; முக்கியமாக பாலிஹவுஸ் மற்றும் அடர்த்தியான நடவில் பிரச்சினை.",
            "symptoms": (
                "இலையின் மேற்பரப்பில் வெளிர் பச்சை முதல் மஞ்சள் நிறத் திட்டுகள்; "
                "நேரடியாக அதன் அடிப்புறத்தில் ஆலிவ் பச்சை முதல் சாம்பல் பழுப்பு நிற "
                "வெல்வெட் போன்ற பூஞ்சை. பழைய இலைகள் முதலில் பாதிக்கப்படும். "
                "மோசமாகப் பாதிக்கப்பட்ட இலைகள் சுருண்டு, வாடி உதிரும்."
            ),
            "cause": (
                "சுமார் 85%க்கு மேல் ஈரப்பதமும் மோசமான காற்றோட்டமும் இருக்கும்போது "
                "வேகமாகப் பெருகும்; அதனால்தான் பாலிஹவுஸ், அடர்த்தியான நடவு மற்றும் "
                "நீண்ட ஈரமான காலங்களில் இது அதிகம்."
            ),
            "immediate_actions": [
                "காற்றோட்டத்தை அதிகரிக்கவும் — பாலிஹவுஸ் பக்கங்களைத் திறக்கவும், அல்லது அடர்த்தியான செடிகளை மெலிதாக்கவும்.",
                "இலைப்பரப்பினூடே காற்று செல்ல கீழ் இலைகளைக் கத்தரிக்கவும்.",
                "பாதிக்கப்பட்ட இலைகளை அகற்றி அழிக்கவும்.",
                "காலையில் அடிப்பகுதியில் நீர் பாய்ச்சி இலைகள் விரைவில் உலரச் செய்யவும்.",
            ],
            "prevention": [
                "கிடைக்கும் இடங்களில் நோய் எதிர்ப்பு ரகங்களைப் பயிரிடவும்.",
                "ஈரப்பதம் அறியப்பட்ட பிரச்சினையாக இருந்தால் வழக்கத்தைவிட அதிக இடைவெளியில் நடவும்.",
                "மருந்து தெளிப்பை நம்பாமல் காற்றோட்டத்தால் ஈரப்பதத்தைக் குறைக்கவும்.",
                "அறுவடைக்குப் பிறகு பயிர்க் கழிவுகளை முழுவதுமாக அகற்றவும் — பூஞ்சை அதில் உயிர் வாழும்.",
            ],
            "expert_note": (
                "காற்றோட்டமும் கத்தரிப்பும் நோயைக் குறைக்கவில்லை என்றால், வேதிக் "
                "கட்டுப்பாட்டைப் பயன்படுத்தும் முன் வேளாண் அலுவலரை அணுகவும்."
            ),
        },
    },
    ("potato", "early_blight"): {
        "name": "Potato Early Blight",
        "severity": SEVERITY_MODERATE,
        "en": {
            "summary": "A fungal leaf spot that hits stressed and older plants hardest.",
            "symptoms": (
                "Dark brown spots with concentric rings on the older, lower leaves, often with "
                "a yellow border. Affected leaves yellow and die back from the bottom of the "
                "plant upward. Tubers may show dark, sunken, leathery patches."
            ),
            "cause": (
                "The fungus survives in soil and crop debris. Warm humid weather, poor "
                "nutrition and water stress all make plants far more vulnerable."
            ),
            "immediate_actions": [
                "Remove and destroy affected lower leaves.",
                "Keep the crop evenly watered — drought-stressed plants are hit hardest.",
                "Make sure the crop has enough nitrogen; deficiency worsens the disease.",
                "Earth up the ridges well to protect the developing tubers.",
                "Switch from overhead irrigation to furrow or drip if you can.",
            ],
            "prevention": [
                "Rotate with non-solanaceous crops (avoid potato, tomato, brinjal).",
                "Use certified seed tubers.",
                "Destroy all crop debris after harvest.",
                "Harvest only when the tubers are fully mature with set skins.",
            ],
            "expert_note": (
                "If the disease keeps spreading after improving nutrition and watering, ask "
                "your agricultural officer about locally approved fungicides."
            ),
        },
        "ta": {
            "summary": "அழுத்தத்தில் உள்ள, வயதான செடிகளை அதிகம் பாதிக்கும் பூஞ்சை இலைப்புள்ளி நோய்.",
            "symptoms": (
                "பழைய கீழ் இலைகளில் ஒன்றுக்குள் ஒன்றாக வளையங்களைக் கொண்ட அடர் பழுப்புப் "
                "புள்ளிகள், பெரும்பாலும் மஞ்சள் விளிம்புடன். பாதிக்கப்பட்ட இலைகள் "
                "மஞ்சளாகி செடியின் அடியிலிருந்து மேல்நோக்கி காய்ந்து போகும். "
                "கிழங்குகளில் அடர் நிற, உள்ளடங்கிய, தோல் போன்ற திட்டுகள் தோன்றலாம்."
            ),
            "cause": (
                "இப்பூஞ்சை மண்ணிலும் பயிர்க் கழிவுகளிலும் உயிர் வாழ்கிறது. வெப்பமான "
                "ஈரமான காலநிலை, போதிய ஊட்டச்சத்து இன்மை, நீர் பற்றாக்குறை ஆகியவை "
                "செடிகளை மிக எளிதில் பாதிக்கச் செய்யும்."
            ),
            "immediate_actions": [
                "பாதிக்கப்பட்ட கீழ் இலைகளை அகற்றி அழிக்கவும்.",
                "பயிருக்குச் சீரான நீர்ப்பாசனம் அளிக்கவும் — வறட்சி அழுத்தத்தில் உள்ள செடிகள் அதிகம் பாதிக்கப்படும்.",
                "பயிருக்குப் போதிய தழைச்சத்து உள்ளதா என உறுதி செய்யவும்; பற்றாக்குறை நோயை மோசமாக்கும்.",
                "வளரும் கிழங்குகளைப் பாதுகாக்க வரப்புகளில் நன்கு மண் அணைக்கவும்.",
                "முடிந்தால் மேல்நீர்ப்பாசனத்திலிருந்து சால் அல்லது சொட்டு நீர்ப்பாசனத்திற்கு மாறவும்.",
            ],
            "prevention": [
                "சோலனேசி அல்லாத பயிர்களுடன் சுழற்சி செய்யவும் (உருளை, தக்காளி, கத்தரியைத் தவிர்க்கவும்).",
                "சான்றளிக்கப்பட்ட விதைக் கிழங்குகளைப் பயன்படுத்தவும்.",
                "அறுவடைக்குப் பிறகு அனைத்துப் பயிர்க் கழிவுகளையும் அழிக்கவும்.",
                "கிழங்குகள் முற்றி தோல் இறுகிய பிறகே அறுவடை செய்யவும்.",
            ],
            "expert_note": (
                "ஊட்டச்சத்தையும் நீர்ப்பாசனத்தையும் மேம்படுத்திய பிறகும் நோய் "
                "பரவினால், அனுமதிக்கப்பட்ட பூஞ்சைக் கொல்லிகள் குறித்து வேளாண் "
                "அலுவலரிடம் கேளுங்கள்."
            ),
        },
    },
    ("potato", "late_blight"): {
        "name": "Potato Late Blight",
        "severity": SEVERITY_HIGH,
        "en": {
            "summary": "The most destructive potato disease there is — it can rot the entire crop.",
            "symptoms": (
                "Dark water-soaked lesions on leaves, often ringed with a pale green halo, "
                "with white fuzzy growth on the underside in humid weather. Stems blacken. "
                "Tubers develop reddish-brown granular rot beneath the skin."
            ),
            "cause": (
                "Phytophthora infestans, favoured by cool nights, warm damp days and long "
                "leaf wetness. Spores spread rapidly by wind and rain and survive in infected "
                "seed tubers and cull piles."
            ),
            "immediate_actions": [
                "Treat this as an emergency — report it early.",
                "Destroy affected plants and any volunteer potatoes immediately.",
                "Earth up the ridges thoroughly so spores cannot wash down to the tubers.",
                "Stop overhead irrigation.",
                "Harvest only in dry conditions, and never store visibly infected tubers.",
            ],
            "prevention": [
                "Plant only certified, healthy seed tubers.",
                "Choose resistant varieties where available.",
                "Never leave cull piles of old potatoes near the field.",
                "Keep a close watch during cool, damp weather.",
            ],
            "expert_note": (
                "Contact your agricultural extension officer immediately for the control "
                "measure approved in your district. Late blight rarely stops without one."
            ),
        },
        "ta": {
            "summary": "உருளைக்கிழங்கின் மிக அழிவுகரமான நோய் — பயிர் முழுவதையும் அழுகச் செய்யும்.",
            "symptoms": (
                "இலைகளில் அடர் நிற நீரூறிய புண்கள், பெரும்பாலும் வெளிர் பச்சை வளையத்துடன்; "
                "ஈரமான காலநிலையில் அடிப்புறத்தில் வெண்மையான பஞ்சு போன்ற வளர்ச்சி. "
                "தண்டுகள் கருப்பாகும். கிழங்குகளின் தோலுக்கு அடியில் சிவப்பு-பழுப்பு "
                "நிற சொரசொரப்பான அழுகல் ஏற்படும்."
            ),
            "cause": (
                "பைட்டோப்தோரா இன்ஃபெஸ்டான்ஸ்; குளிர்ந்த இரவுகள், வெதுவெதுப்பான ஈரமான "
                "பகல்கள், நீண்ட நேரம் இலை ஈரமாக இருப்பது ஆகியவை இதற்கு உகந்தவை. "
                "வித்திகள் காற்றிலும் மழையிலும் வேகமாகப் பரவி, பாதிக்கப்பட்ட விதைக் "
                "கிழங்குகளிலும் கழிவுக் குவியல்களிலும் உயிர் வாழும்."
            ),
            "immediate_actions": [
                "இதை அவசர நிலையாகக் கருதவும் — ஆரம்பத்திலேயே தெரிவிக்கவும்.",
                "பாதிக்கப்பட்ட செடிகளையும் தானாக முளைத்த உருளைச் செடிகளையும் உடனே அழிக்கவும்.",
                "வித்திகள் கிழங்கு வரை கழுவிச் செல்லாதவாறு வரப்புகளில் நன்கு மண் அணைக்கவும்.",
                "மேலிருந்து நீர் பாய்ச்சுவதை நிறுத்தவும்.",
                "உலர்ந்த சூழலில் மட்டும் அறுவடை செய்யவும்; பாதிக்கப்பட்ட கிழங்குகளைச் சேமிக்கவே வேண்டாம்.",
            ],
            "prevention": [
                "சான்றளிக்கப்பட்ட ஆரோக்கியமான விதைக் கிழங்குகளை மட்டுமே நடவும்.",
                "கிடைக்கும் இடங்களில் நோய் எதிர்ப்பு ரகங்களைத் தேர்வு செய்யவும்.",
                "வயலுக்கு அருகில் பழைய உருளைக்கிழங்குக் கழிவுக் குவியல்களை வைக்கவே வேண்டாம்.",
                "குளிர்ந்த ஈரமான காலநிலையில் உன்னிப்பாகக் கண்காணிக்கவும்.",
            ],
            "expert_note": (
                "உங்கள் மாவட்டத்தில் அனுமதிக்கப்பட்ட கட்டுப்பாட்டு முறைக்காக உடனடியாக "
                "வேளாண் விரிவாக்க அலுவலரைத் தொடர்பு கொள்ளவும். மருந்து இல்லாமல் "
                "இந்நோய் அரிதாகவே நிற்கும்."
            ),
        },
    },
    ("corn", "common_rust"): {
        "name": "Maize Common Rust",
        "severity": SEVERITY_LOW,
        "en": {
            "summary": "Usually cosmetic late in the season; only serious if it strikes young plants.",
            "symptoms": (
                "Small, powdery, reddish-brown pustules scattered on both surfaces of the "
                "leaf. Rubbing them leaves a rusty stain on your fingers. Heavy infection "
                "turns leaves yellow and dries them early."
            ),
            "cause": (
                "Spores blow in on the wind from other regions. Moderate temperatures with "
                "heavy dew or high humidity favour it."
            ),
            "immediate_actions": [
                "Check how much of the leaf area is actually affected before acting.",
                "Late-season, light infection on mature plants needs no treatment at all.",
                "Remove volunteer maize plants that keep the fungus alive between crops.",
            ],
            "prevention": [
                "Grow resistant hybrids — this is by far the most effective and cheapest control.",
                "Avoid very late or heavily staggered planting dates.",
                "Do not plant maize continuously in the same field.",
            ],
            "expert_note": (
                "If rust appears early, before tasselling, and is spreading fast, consult your "
                "agricultural officer — only then is a spray usually worth the cost."
            ),
        },
        "ta": {
            "summary": "பருவ இறுதியில் பொதுவாகப் பெரிய பாதிப்பில்லை; இளம் செடிகளைத் தாக்கினால் மட்டுமே தீவிரம்.",
            "symptoms": (
                "இலையின் இரு பக்கங்களிலும் சிதறிக் காணப்படும் சிறிய, தூள் போன்ற, "
                "சிவப்பு-பழுப்பு நிறக் கொப்புளங்கள். அவற்றைத் தேய்த்தால் விரலில் "
                "துரு போன்ற கறை படியும். கடுமையான தாக்குதலில் இலைகள் மஞ்சளாகி "
                "விரைவில் உலர்ந்துவிடும்."
            ),
            "cause": (
                "வித்திகள் பிற பகுதிகளிலிருந்து காற்றில் வந்து சேரும். மிதமான "
                "வெப்பநிலையுடன் அதிக பனி அல்லது ஈரப்பதம் இதற்கு உகந்தது."
            ),
            "immediate_actions": [
                "நடவடிக்கை எடுப்பதற்கு முன் இலைப்பரப்பில் எவ்வளவு பாதிக்கப்பட்டுள்ளது என்பதைப் பாருங்கள்.",
                "முதிர்ந்த செடிகளில் பருவ இறுதியில் ஏற்படும் லேசான தாக்குதலுக்கு எந்த மருந்தும் தேவையில்லை.",
                "பயிர்களுக்கு இடையே பூஞ்சையை உயிருடன் வைத்திருக்கும், தானாக முளைத்த சோளச் செடிகளை அகற்றவும்.",
            ],
            "prevention": [
                "நோய் எதிர்ப்பு ஒட்டு ரகங்களைப் பயிரிடவும் — இதுவே மிகச் சிறந்த, மலிவான கட்டுப்பாடு.",
                "மிகவும் தாமதமான அல்லது பல கட்டங்களாகப் பிரிந்த விதைப்பைத் தவிர்க்கவும்.",
                "ஒரே வயலில் தொடர்ந்து சோளத்தை மட்டும் பயிரிட வேண்டாம்.",
            ],
            "expert_note": (
                "கதிர் வருவதற்கு முன்பே துரு தோன்றி வேகமாகப் பரவினால் வேளாண் "
                "அலுவலரை அணுகவும் — அப்போது மட்டுமே மருந்து தெளிப்பு செலவுக்கு ஏற்றது."
            ),
        },
    },
    ("corn", "northern_leaf_blight"): {
        "name": "Maize Northern Leaf Blight",
        "severity": SEVERITY_MODERATE,
        "en": {
            "summary": "Long grey lesions that can cost real yield if they reach the upper leaves early.",
            "symptoms": (
                "Long, cigar-shaped grey-green to tan lesions running lengthwise along the "
                "leaf, typically 3-15 cm long. They start on the lower leaves and move upward. "
                "Severe infection makes the whole plant look scorched."
            ),
            "cause": (
                "The fungus survives on infected maize stubble. Moderate temperatures with "
                "long periods of leaf wetness or heavy dew let it spread."
            ),
            "immediate_actions": [
                "Note how far up the plant the lesions have reached — damage above the cob matters most.",
                "Avoid working through the crop while the leaves are wet.",
                "Plan to plough in or remove infected stubble after harvest.",
            ],
            "prevention": [
                "Choose resistant hybrids where available.",
                "Rotate maize with a non-host crop for at least one season.",
                "Bury or remove crop residue — the fungus overwinters on old stubble.",
                "Avoid very dense planting so the canopy dries faster.",
            ],
            "expert_note": (
                "If lesions appear on the upper leaves before or around tasselling, ask your "
                "agricultural officer about approved fungicides — that is when yield loss "
                "becomes significant."
            ),
        },
        "ta": {
            "summary": "நீளமான சாம்பல் நிறப் புண்கள்; மேல் இலைகளை முன்கூட்டியே தாக்கினால் மகசூல் இழப்பு ஏற்படும்.",
            "symptoms": (
                "இலையின் நீளவாக்கில் நீண்ட, சுருட்டு வடிவ, சாம்பல்-பச்சை முதல் மண் "
                "நிறப் புண்கள், பொதுவாக 3-15 செ.மீ நீளம். கீழ் இலைகளில் தொடங்கி "
                "மேல்நோக்கி நகரும். கடுமையான தாக்குதலில் செடி முழுவதும் "
                "கருகியது போலத் தோன்றும்."
            ),
            "cause": (
                "இப்பூஞ்சை பாதிக்கப்பட்ட சோளத் தாள்களில் உயிர் வாழ்கிறது. மிதமான "
                "வெப்பநிலையுடன் நீண்ட நேரம் இலை ஈரமாக இருப்பது அல்லது அதிக பனி "
                "இதைப் பரவச் செய்யும்."
            ),
            "immediate_actions": [
                "புண்கள் செடியில் எவ்வளவு உயரம் வரை பரவியுள்ளன எனப் பாருங்கள் — கதிருக்கு மேல் ஏற்படும் பாதிப்பே முக்கியம்.",
                "இலைகள் ஈரமாக இருக்கும்போது பயிரினூடே வேலை செய்வதைத் தவிர்க்கவும்.",
                "அறுவடைக்குப் பிறகு பாதிக்கப்பட்ட தாள்களை உழுது மண்ணில் சேர்க்க அல்லது அகற்றத் திட்டமிடவும்.",
            ],
            "prevention": [
                "கிடைக்கும் இடங்களில் நோய் எதிர்ப்பு ஒட்டு ரகங்களைத் தேர்வு செய்யவும்.",
                "குறைந்தது ஒரு பருவமாவது சோளத்தை வேறு பயிருடன் சுழற்சி செய்யவும்.",
                "பயிர்க் கழிவுகளைப் புதைக்கவும் அல்லது அகற்றவும் — பூஞ்சை பழைய தாள்களில் உயிர் வாழும்.",
                "இலைப்பரப்பு விரைவில் உலர மிக அடர்த்தியான விதைப்பைத் தவிர்க்கவும்.",
            ],
            "expert_note": (
                "கதிர் வருவதற்கு முன் அல்லது அப்போது மேல் இலைகளில் புண்கள் தோன்றினால், "
                "அனுமதிக்கப்பட்ட பூஞ்சைக் கொல்லிகள் குறித்து வேளாண் அலுவலரிடம் "
                "கேளுங்கள் — அப்போதுதான் மகசூல் இழப்பு கணிசமாகும்."
            ),
        },
    },
    ("rice", "leaf_blast"): {
        "name": "Rice Leaf Blast",
        "severity": SEVERITY_HIGH,
        "en": {
            "summary": "A serious rice disease; the neck-infecting stage can destroy the grain entirely.",
            "symptoms": (
                "Spindle- or diamond-shaped lesions with grey or whitish centres and brown to "
                "reddish margins. Lesions merge and kill whole leaves. If it reaches the neck "
                "of the panicle, the node blackens and the grain fails to fill."
            ),
            "cause": (
                "Favoured by excess nitrogen, long leaf wetness, high humidity, cool nights "
                "and drought-stressed upland fields. Over-fertilised crops are far more "
                "susceptible."
            ),
            "immediate_actions": [
                "Stop any further nitrogen top-dressing immediately.",
                "Keep a stable water level in the field — avoid letting it dry out.",
                "Check the panicle necks; neck blast is far more damaging than leaf blast.",
                "Remove and destroy severely infected plants and nearby weed hosts.",
            ],
            "prevention": [
                "Split nitrogen into several doses instead of applying it all at once.",
                "Grow resistant varieties suited to your district.",
                "Use clean, treated seed.",
                "Destroy infected stubble and straw after harvest.",
                "Avoid very dense transplanting.",
            ],
            "expert_note": (
                "Consult your agricultural officer promptly if blast appears at the seedling "
                "or neck stage — timing of any spray is critical and dosage must come from them."
            ),
        },
        "ta": {
            "summary": "நெல்லின் தீவிர நோய்; கழுத்தைத் தாக்கும் நிலை தானியத்தை முற்றிலும் அழிக்கும்.",
            "symptoms": (
                "சாம்பல் அல்லது வெண்மையான மையமும், பழுப்பு முதல் சிவப்பு விளிம்பும் "
                "கொண்ட தக்கை அல்லது வைர வடிவப் புண்கள். புண்கள் ஒன்றிணைந்து இலைகளை "
                "முழுவதுமாக அழிக்கும். கதிரின் கழுத்தை அடைந்தால் கணு கருப்பாகி "
                "தானியம் நிரம்பாமல் போகும்."
            ),
            "cause": (
                "அதிக தழைச்சத்து, நீண்ட நேரம் இலை ஈரமாக இருப்பது, அதிக ஈரப்பதம், "
                "குளிர்ந்த இரவுகள், வறட்சி அழுத்தத்தில் உள்ள மேட்டுநிலம் ஆகியவை "
                "இதற்கு உகந்தவை. அதிக உரமிட்ட பயிர்கள் மிக எளிதில் பாதிக்கப்படும்."
            ),
            "immediate_actions": [
                "மேலும் தழைச்சத்து உரமிடுவதை உடனே நிறுத்தவும்.",
                "வயலில் நீர் மட்டத்தைச் சீராக வைத்திருக்கவும் — வயல் காய்ந்துவிடக் கூடாது.",
                "கதிரின் கழுத்துகளைப் பரிசோதிக்கவும்; கழுத்து நோய் இலை நோயைவிட மிக அதிக சேதம் விளைவிக்கும்.",
                "கடுமையாகப் பாதிக்கப்பட்ட செடிகளையும் அருகிலுள்ள களைகளையும் அகற்றி அழிக்கவும்.",
            ],
            "prevention": [
                "தழைச்சத்தை ஒரே முறையில் இடாமல் பல தவணைகளாகப் பிரித்து இடவும்.",
                "உங்கள் மாவட்டத்திற்கு ஏற்ற நோய் எதிர்ப்பு ரகங்களைப் பயிரிடவும்.",
                "சுத்தமான, விதை நேர்த்தி செய்யப்பட்ட விதைகளைப் பயன்படுத்தவும்.",
                "அறுவடைக்குப் பிறகு பாதிக்கப்பட்ட தாள்களையும் வைக்கோலையும் அழிக்கவும்.",
                "மிக அடர்த்தியான நடவைத் தவிர்க்கவும்.",
            ],
            "expert_note": (
                "நாற்று அல்லது கழுத்து நிலையில் நோய் தோன்றினால் உடனே வேளாண் அலுவலரை "
                "அணுகவும் — மருந்து தெளிக்கும் நேரம் மிக முக்கியம், அளவை அவர்களே "
                "சொல்ல வேண்டும்."
            ),
        },
    },
    ("rice", "bacterial_leaf_blight"): {
        "name": "Rice Bacterial Leaf Blight",
        "severity": SEVERITY_HIGH,
        "en": {
            "summary": "A bacterial disease — fungicides will not work on it.",
            "symptoms": (
                "Yellow to white wavy-edged lesions starting at the leaf tips and margins and "
                "spreading downward. Lesions dry to a straw colour. In young plants the whole "
                "seedling can wilt and die (kresek). Milky bacterial ooze may appear on cut "
                "leaves held in water."
            ),
            "cause": (
                "The bacterium enters through wounds and natural leaf pores. Spread by "
                "irrigation water, heavy rain, strong wind and by handling wet plants. Excess "
                "nitrogen and flooding make it worse."
            ),
            "immediate_actions": [
                "Do not spray fungicide — it has no effect on bacteria and wastes money.",
                "Stop further nitrogen application.",
                "Drain the field periodically where the crop stage allows.",
                "Remove infected plant debris and weed hosts around the bunds.",
                "Avoid moving between fields while plants are wet.",
            ],
            "prevention": [
                "Use resistant varieties — this is the main practical control.",
                "Use certified, clean seed.",
                "Avoid injuring seedlings during transplanting; wounds are the entry point.",
                "Keep balanced nutrition rather than heavy nitrogen.",
                "Destroy stubble and volunteer plants after harvest.",
            ],
            "expert_note": (
                "Report outbreaks to your agricultural extension officer — variety choice for "
                "the next season is the real solution and they will know what performs "
                "locally."
            ),
        },
        "ta": {
            "summary": "இது ஒரு பாக்டீரியா நோய் — பூஞ்சைக் கொல்லிகள் இதற்கு வேலை செய்யாது.",
            "symptoms": (
                "இலை நுனிகளிலும் விளிம்புகளிலும் தொடங்கி கீழ்நோக்கிப் பரவும் மஞ்சள் "
                "முதல் வெண்மை நிற அலை வடிவ விளிம்புள்ள புண்கள். புண்கள் உலர்ந்து "
                "வைக்கோல் நிறமாகும். இளம் செடிகளில் நாற்று முழுவதும் வாடி இறக்கும். "
                "வெட்டப்பட்ட இலையை நீரில் வைத்தால் பால் போன்ற பாக்டீரியா ஊறல் தெரியும்."
            ),
            "cause": (
                "பாக்டீரியா காயங்கள் வழியாகவும் இலையின் இயற்கைத் துளைகள் வழியாகவும் "
                "உள்ளே நுழைகிறது. பாசன நீர், கனமழை, பலத்த காற்று, ஈரமான செடிகளைக் "
                "கையாள்வது ஆகியவற்றால் பரவும். அதிக தழைச்சத்தும் நீர் தேங்குதலும் "
                "நோயை மோசமாக்கும்."
            ),
            "immediate_actions": [
                "பூஞ்சைக் கொல்லி தெளிக்க வேண்டாம் — பாக்டீரியாவுக்கு அது வேலை செய்யாது, பணம் வீணாகும்.",
                "மேலும் தழைச்சத்து உரமிடுவதை நிறுத்தவும்.",
                "பயிர் நிலை அனுமதிக்கும் இடங்களில் அவ்வப்போது வயலில் நீரை வடித்துவிடவும்.",
                "பாதிக்கப்பட்ட பயிர்க் கழிவுகளையும் வரப்புகளைச் சுற்றியுள்ள களைகளையும் அகற்றவும்.",
                "செடிகள் ஈரமாக இருக்கும்போது வயல்களுக்கு இடையே நடமாடுவதைத் தவிர்க்கவும்.",
            ],
            "prevention": [
                "நோய் எதிர்ப்பு ரகங்களைப் பயன்படுத்தவும் — இதுவே முக்கியமான நடைமுறைக் கட்டுப்பாடு.",
                "சான்றளிக்கப்பட்ட சுத்தமான விதைகளைப் பயன்படுத்தவும்.",
                "நடவின்போது நாற்றுகளுக்குக் காயம் ஏற்படுத்த வேண்டாம்; காயங்களே நுழைவு வழி.",
                "அதிக தழைச்சத்துக்குப் பதிலாக சமச்சீரான ஊட்டச்சத்தை அளிக்கவும்.",
                "அறுவடைக்குப் பிறகு தாள்களையும் தானாக முளைத்த செடிகளையும் அழிக்கவும்.",
            ],
            "expert_note": (
                "நோய்ப் பரவலை வேளாண் விரிவாக்க அலுவலரிடம் தெரிவிக்கவும் — அடுத்த "
                "பருவத்திற்கான ரகத் தேர்வே உண்மையான தீர்வு; உங்கள் பகுதியில் எது "
                "சிறப்பாகச் செயல்படுகிறது என்பது அவர்களுக்குத் தெரியும்."
            ),
        },
    },

    ("tomato", "septoria_leaf_spot"): {
        "name": "Tomato Septoria Leaf Spot",
        "severity": SEVERITY_MODERATE,
        "en": {
            "summary": "Many small circular spots with pale centres, spreading upward from the oldest leaves.",
            "symptoms": (
                "Numerous small circular spots, roughly 2-3 mm across, with grey or tan "
                "centres and dark brown borders. Tiny black specks are often visible in the "
                "centre of each spot. It starts on the lowest leaves after fruit set and "
                "works upward. Heavily spotted leaves yellow, dry and fall, exposing fruit "
                "to sunscald."
            ),
            "cause": (
                "The fungus survives on crop debris and on weeds in the nightshade family. "
                "It is splashed onto leaves by rain and overhead watering, and needs long "
                "periods of leaf wetness with warm temperatures."
            ),
            "immediate_actions": [
                "Pick off and destroy the spotted lower leaves as soon as you see them.",
                "Stop overhead watering; water at the base of the plant instead.",
                "Mulch around the base so rain cannot splash soil onto the leaves.",
                "Pull out nightshade-family weeds around the field, which harbour the fungus.",
                "Wash your hands and tools after handling infected plants.",
            ],
            "prevention": [
                "Rotate away from tomato for two to three seasons.",
                "Stake plants and space them widely so leaves dry quickly.",
                "Remove and destroy all crop debris at the end of the season.",
                "Use clean, certified seed.",
            ],
            "expert_note": (
                "If spotting reaches the middle and upper leaves while fruit is still "
                "developing, ask your agricultural officer which fungicide is approved "
                "locally and at what interval."
            ),
        },
        "ta": {
            "summary": "வெளிர் நிற மையம் கொண்ட ஏராளமான சிறு வட்டப் புள்ளிகள்; பழைய இலைகளிலிருந்து மேல்நோக்கிப் பரவும்.",
            "symptoms": (
                "சுமார் 2-3 மி.மீ அளவுள்ள ஏராளமான சிறிய வட்டப் புள்ளிகள்; சாம்பல் "
                "அல்லது மண் நிற மையமும் அடர் பழுப்பு விளிம்பும் கொண்டவை. ஒவ்வொரு "
                "புள்ளியின் மையத்திலும் சிறு கருப்புப் புள்ளிகள் தெரியும். காய் "
                "பிடித்த பிறகு மிகக் கீழ் இலைகளில் தொடங்கி மேல்நோக்கி நகரும். "
                "அதிகம் பாதிக்கப்பட்ட இலைகள் மஞ்சளாகி, உலர்ந்து உதிர்வதால் "
                "காய்கள் வெயிலில் கருகும்."
            ),
            "cause": (
                "இப்பூஞ்சை பயிர்க் கழிவுகளிலும் சோலனேசி குடும்பக் களைகளிலும் உயிர் "
                "வாழ்கிறது. மழை மற்றும் மேல்நீர்ப்பாசனத்தால் இலைகளில் தெறிக்கிறது; "
                "நீண்ட நேரம் இலை ஈரமாக இருப்பதும் வெப்பமான காலநிலையும் தேவை."
            ),
            "immediate_actions": [
                "புள்ளிகள் உள்ள கீழ் இலைகளைக் கண்டவுடன் பறித்து அழிக்கவும்.",
                "மேலிருந்து நீர் பாய்ச்சுவதை நிறுத்தி, அடிப்பகுதியில் நீர் விடவும்.",
                "மழையால் மண் இலைகளில் தெறிக்காமல் இருக்க அடியில் மூடாக்கு இடவும்.",
                "பூஞ்சையைத் தாங்கும் சோலனேசி குடும்பக் களைகளை வயலைச் சுற்றி அகற்றவும்.",
                "பாதிக்கப்பட்ட செடிகளைக் கையாண்ட பிறகு கைகளையும் கருவிகளையும் கழுவவும்.",
            ],
            "prevention": [
                "இரண்டு முதல் மூன்று பருவங்களுக்குத் தக்காளியைத் தவிர்த்துப் பயிர் சுழற்சி செய்யவும்.",
                "செடிகளுக்குக் கழி கட்டி, அதிக இடைவெளி விட்டு இலைகள் விரைவில் உலரச் செய்யவும்.",
                "பருவ முடிவில் அனைத்துப் பயிர்க் கழிவுகளையும் அகற்றி அழிக்கவும்.",
                "சுத்தமான, சான்றளிக்கப்பட்ட விதைகளைப் பயன்படுத்தவும்.",
            ],
            "expert_note": (
                "காய் வளரும் நிலையிலேயே நடு மற்றும் மேல் இலைகளுக்குப் புள்ளிகள் "
                "பரவினால், அனுமதிக்கப்பட்ட பூஞ்சைக் கொல்லி எது, எவ்வளவு இடைவெளியில் "
                "என்பதை வேளாண் அலுவலரிடம் கேளுங்கள்."
            ),
        },
    },
    ("tomato", "bacterial_spot"): {
        "name": "Tomato Bacterial Spot",
        "severity": SEVERITY_MODERATE,
        "en": {
            "summary": "A bacterial disease — fungicides will not cure it, and seed hygiene matters most.",
            "symptoms": (
                "Small, dark, greasy-looking spots on leaves, often with a yellow halo, that "
                "may dry and tear leaving ragged holes. Fruit develops raised, scabby, brown "
                "spots that make it unsellable. Spots stay small and angular rather than "
                "forming large rings."
            ),
            "cause": (
                "Bacteria carried on seed and transplants, spread by rain splash, overhead "
                "irrigation, wind-driven rain and handling wet plants. Warm, wet weather "
                "favours it strongly."
            ),
            "immediate_actions": [
                "Do not rely on ordinary fungicides — this is a bacterium, not a fungus.",
                "Remove and destroy badly affected leaves and fruit.",
                "Stop overhead irrigation immediately.",
                "Never work among the plants while they are wet — this is how it spreads.",
                "Disinfect tools and stakes between plants.",
            ],
            "prevention": [
                "Use certified, disease-free seed and healthy transplants — this is the main control.",
                "Rotate away from tomato and chilli for at least two years.",
                "Destroy crop debris promptly after harvest.",
                "Avoid working in the field after rain or heavy dew.",
            ],
            "expert_note": (
                "Ask your agricultural officer about copper-based options approved in your "
                "area. Bacterial spot is managed, not cured, so they will focus on seed "
                "source and rotation for the next season."
            ),
        },
        "ta": {
            "summary": "பாக்டீரியா நோய் — பூஞ்சைக் கொல்லிகள் குணப்படுத்தாது; விதைத் தூய்மையே முக்கியம்.",
            "symptoms": (
                "இலைகளில் சிறிய, அடர் நிற, எண்ணெய்த்தன்மையுள்ள புள்ளிகள்; பெரும்பாலும் "
                "மஞ்சள் வளையத்துடன். இவை உலர்ந்து கிழிந்து இலையில் ஓட்டைகளை "
                "ஏற்படுத்தும். காய்களில் மேடான, சொரசொரப்பான பழுப்புப் புள்ளிகள் "
                "தோன்றி விற்பனைக்கு உதவாமல் போகும். புள்ளிகள் பெரிய வளையங்களாக "
                "மாறாமல் சிறியதாகவே இருக்கும்."
            ),
            "cause": (
                "விதை மற்றும் நாற்றுகள் வழியாகப் பரவும் பாக்டீரியா; மழைத் தெறிப்பு, "
                "மேல்நீர்ப்பாசனம், காற்றுடன் கூடிய மழை, ஈரமான செடிகளைக் கையாள்வது "
                "ஆகியவற்றால் பரவும். வெப்பமான ஈரமான காலநிலை இதற்கு மிக உகந்தது."
            ),
            "immediate_actions": [
                "சாதாரண பூஞ்சைக் கொல்லிகளை நம்ப வேண்டாம் — இது பூஞ்சை அல்ல, பாக்டீரியா.",
                "மோசமாகப் பாதிக்கப்பட்ட இலைகளையும் காய்களையும் அகற்றி அழிக்கவும்.",
                "மேலிருந்து நீர் பாய்ச்சுவதை உடனே நிறுத்தவும்.",
                "செடிகள் ஈரமாக இருக்கும்போது அவற்றுக்கு இடையே வேலை செய்யவே வேண்டாம் — இப்படித்தான் பரவுகிறது.",
                "செடிகளுக்கு இடையே கருவிகளையும் கழிகளையும் கிருமி நீக்கம் செய்யவும்.",
            ],
            "prevention": [
                "சான்றளிக்கப்பட்ட நோயற்ற விதைகளையும் ஆரோக்கியமான நாற்றுகளையும் பயன்படுத்தவும் — இதுவே முக்கியக் கட்டுப்பாடு.",
                "குறைந்தது இரண்டு ஆண்டுகள் தக்காளி, மிளகாயைத் தவிர்த்துப் பயிர் சுழற்சி செய்யவும்.",
                "அறுவடைக்குப் பிறகு பயிர்க் கழிவுகளை உடனே அழிக்கவும்.",
                "மழை அல்லது அதிக பனிக்குப் பிறகு வயலில் வேலை செய்வதைத் தவிர்க்கவும்.",
            ],
            "expert_note": (
                "உங்கள் பகுதியில் அனுமதிக்கப்பட்ட காப்பர் அடிப்படையிலான தேர்வுகள் "
                "குறித்து வேளாண் அலுவலரிடம் கேளுங்கள். இந்நோயைக் குணப்படுத்த முடியாது, "
                "நிர்வகிக்க மட்டுமே முடியும்; எனவே அடுத்த பருவத்திற்கான விதை ஆதாரம் "
                "மற்றும் பயிர் சுழற்சியில் அவர்கள் கவனம் செலுத்துவார்கள்."
            ),
        },
    },
    ("tomato", "target_spot"): {
        "name": "Tomato Target Spot",
        "severity": SEVERITY_MODERATE,
        "en": {
            "summary": "Ring-patterned spots that can also pit the fruit.",
            "symptoms": (
                "Brown spots with light centres and concentric rings, on leaves, stems and "
                "fruit. On fruit it forms small sunken pits that enlarge. Heavy infection "
                "causes rapid leaf drop."
            ),
            "cause": (
                "A fungus favoured by prolonged leaf wetness, high humidity and dense "
                "canopies. It survives on crop residue between seasons."
            ),
            "immediate_actions": [
                "Remove affected leaves and any pitted fruit.",
                "Prune the lower canopy to improve airflow.",
                "Switch to base watering and water early in the day.",
            ],
            "prevention": [
                "Rotate with non-solanaceous crops.",
                "Avoid dense planting and heavy nitrogen, which thicken the canopy.",
                "Destroy crop residue after harvest.",
            ],
            "expert_note": (
                "Consult your agricultural officer if fruit is being pitted, since that is a "
                "direct loss of marketable yield."
            ),
        },
        "ta": {
            "summary": "வளைய வடிவப் புள்ளிகள்; காய்களிலும் குழிகளை ஏற்படுத்தும்.",
            "symptoms": (
                "இலைகள், தண்டுகள், காய்கள் ஆகியவற்றில் வெளிர் மையமும் ஒன்றுக்குள் "
                "ஒன்றாக வளையங்களும் கொண்ட பழுப்புப் புள்ளிகள். காய்களில் சிறிய "
                "உள்ளடங்கிய குழிகள் உருவாகிப் பெரிதாகும். கடுமையான தாக்குதலில் "
                "இலைகள் வேகமாக உதிரும்."
            ),
            "cause": (
                "நீண்ட நேரம் இலை ஈரமாக இருப்பது, அதிக ஈரப்பதம், அடர்த்தியான "
                "இலைப்பரப்பு ஆகியவற்றால் பெருகும் பூஞ்சை. பருவங்களுக்கு இடையே "
                "பயிர்க் கழிவுகளில் உயிர் வாழும்."
            ),
            "immediate_actions": [
                "பாதிக்கப்பட்ட இலைகளையும் குழி விழுந்த காய்களையும் அகற்றவும்.",
                "காற்றோட்டத்தை மேம்படுத்த கீழ் இலைப்பரப்பைக் கத்தரிக்கவும்.",
                "அடிப்பகுதி நீர்ப்பாசனத்திற்கு மாறி, காலையில் நீர் விடவும்.",
            ],
            "prevention": [
                "சோலனேசி அல்லாத பயிர்களுடன் சுழற்சி செய்யவும்.",
                "அடர்த்தியான நடவையும் அதிக தழைச்சத்தையும் தவிர்க்கவும்.",
                "அறுவடைக்குப் பிறகு பயிர்க் கழிவுகளை அழிக்கவும்.",
            ],
            "expert_note": (
                "காய்களில் குழிகள் விழுந்தால் அது நேரடி மகசூல் இழப்பு என்பதால் "
                "வேளாண் அலுவலரை அணுகவும்."
            ),
        },
    },
    ("tomato", "spider_mites"): {
        "name": "Tomato Spider Mites",
        "severity": SEVERITY_MODERATE,
        "en": {
            "summary": "A pest, not a disease — tiny mites feeding on the underside of leaves.",
            "symptoms": (
                "Fine pale stippling or speckling on the upper leaf surface. Turn a leaf "
                "over and you may see very fine webbing and tiny moving specks. Leaves turn "
                "bronze or yellow and dry out. Worst in hot, dry, dusty conditions."
            ),
            "cause": (
                "Two-spotted spider mites multiply explosively in hot dry weather, "
                "especially on dusty plants beside paths, and when broad-spectrum "
                "insecticides have killed off their natural predators."
            ),
            "immediate_actions": [
                "Check the underside of the leaves with a magnifying glass to confirm mites.",
                "Spray plants forcefully with plain water to dislodge mites and reduce dust.",
                "Remove and destroy the worst affected leaves.",
                "Stop using broad-spectrum insecticides, which kill the predatory mites that control them.",
                "Keep the crop properly watered — drought-stressed plants suffer far more.",
            ],
            "prevention": [
                "Control dust along field paths and borders.",
                "Encourage natural predators by avoiding unnecessary insecticide sprays.",
                "Inspect plants weekly during hot dry spells so you catch it early.",
            ],
            "expert_note": (
                "If webbing is widespread, ask your agricultural officer about a specific "
                "miticide. Ordinary insecticides do not control mites and often make the "
                "problem worse."
            ),
        },
        "ta": {
            "summary": "இது நோய் அல்ல, பூச்சி — இலையின் அடிப்புறத்தில் உண்ணும் மிகச் சிறிய சிலந்திப் பூச்சிகள்.",
            "symptoms": (
                "இலையின் மேற்பரப்பில் மெல்லிய வெளிர் நிறப் புள்ளிகள். இலையைத் "
                "திருப்பிப் பார்த்தால் மெல்லிய வலையும் நகரும் சிறு புள்ளிகளும் "
                "தெரியலாம். இலைகள் வெண்கல நிறமாகவோ மஞ்சளாகவோ மாறி உலரும். "
                "வெப்பமான, வறண்ட, தூசி நிறைந்த சூழலில் மிக அதிகம்."
            ),
            "cause": (
                "வெப்பமான வறண்ட காலநிலையில் இப்பூச்சிகள் வேகமாகப் பெருகும்; "
                "குறிப்பாக பாதை ஓரங்களில் தூசி படிந்த செடிகளிலும், பரவலான "
                "பூச்சிக்கொல்லிகள் இயற்கை எதிரிகளை அழித்த இடங்களிலும்."
            ),
            "immediate_actions": [
                "பூதக்கண்ணாடி கொண்டு இலையின் அடிப்புறத்தைப் பார்த்துப் பூச்சிகளை உறுதிப்படுத்தவும்.",
                "சாதாரண நீரை வேகமாகத் தெளித்துப் பூச்சிகளை அகற்றி தூசியைக் குறைக்கவும்.",
                "மோசமாகப் பாதிக்கப்பட்ட இலைகளை அகற்றி அழிக்கவும்.",
                "பரவலான பூச்சிக்கொல்லிகளை நிறுத்தவும் — அவை இப்பூச்சிகளைக் கட்டுப்படுத்தும் இயற்கை எதிரிகளைக் கொல்லும்.",
                "பயிருக்குச் சரியான நீர்ப்பாசனம் அளிக்கவும் — வறட்சியில் உள்ள செடிகள் அதிகம் பாதிக்கப்படும்.",
            ],
            "prevention": [
                "வயல் பாதைகள் மற்றும் எல்லைகளில் தூசியைக் கட்டுப்படுத்தவும்.",
                "தேவையற்ற பூச்சிக்கொல்லித் தெளிப்பைத் தவிர்த்து இயற்கை எதிரிகளை ஊக்குவிக்கவும்.",
                "வெப்பமான வறண்ட காலங்களில் வாரந்தோறும் செடிகளைப் பரிசோதிக்கவும்.",
            ],
            "expert_note": (
                "வலை பரவலாகத் தெரிந்தால், தனிப்பட்ட பூச்சிக்கொல்லி (miticide) குறித்து "
                "வேளாண் அலுவலரிடம் கேளுங்கள். சாதாரண பூச்சிக்கொல்லிகள் இவற்றைக் "
                "கட்டுப்படுத்தாது; பெரும்பாலும் பிரச்சினையை மோசமாக்கும்."
            ),
        },
    },
    ("tomato", "yellow_leaf_curl_virus"): {
        "name": "Tomato Yellow Leaf Curl Virus",
        "severity": SEVERITY_HIGH,
        "en": {
            "summary": "A virus spread by whiteflies. There is no cure — control the whitefly and remove infected plants.",
            "symptoms": (
                "Leaves curl upward and inward, become small, crinkled and yellow at the "
                "margins. Plants are severely stunted and bushy. Infected plants set little "
                "or no fruit. Young plants infected early may produce nothing at all."
            ),
            "cause": (
                "A virus transmitted by the whitefly. It is not spread by touch, tools or "
                "soil — only by the insect. Once a plant is infected it cannot be cured."
            ),
            "immediate_actions": [
                "There is no cure for an infected plant — remove and destroy it to protect the rest.",
                "Bag infected plants before carrying them out so whiteflies do not escape into the field.",
                "Check the underside of leaves for tiny white flying insects.",
                "Control whiteflies, since they are the only way it spreads.",
                "Remove weed hosts around the field.",
            ],
            "prevention": [
                "Grow resistant or tolerant varieties — the single most effective measure.",
                "Raise seedlings under insect-proof net before transplanting.",
                "Use yellow sticky traps to monitor and reduce whitefly numbers.",
                "Avoid planting a new tomato crop next to an old infected one.",
            ],
            "expert_note": (
                "Talk to your agricultural extension officer about resistant varieties and "
                "whitefly management for the next season. This disease is beaten by variety "
                "choice and insect control, not by spraying the sick plants."
            ),
        },
        "ta": {
            "summary": "வெள்ளை ஈயால் பரவும் வைரஸ். மருந்தில்லை — வெள்ளை ஈயைக் கட்டுப்படுத்தி, பாதிக்கப்பட்ட செடிகளை அகற்றவும்.",
            "symptoms": (
                "இலைகள் மேல்நோக்கியும் உள்நோக்கியும் சுருண்டு, சிறியதாகி, "
                "சுருக்கமடைந்து விளிம்புகளில் மஞ்சளாகும். செடிகள் மிகவும் "
                "குள்ளமாகி புதர் போலத் தோன்றும். பாதிக்கப்பட்ட செடிகளில் காய் "
                "மிகக் குறைவாகவே பிடிக்கும் அல்லது பிடிக்காது."
            ),
            "cause": (
                "வெள்ளை ஈ மூலம் பரவும் வைரஸ். தொடுவதாலோ, கருவிகளாலோ, மண்ணாலோ "
                "பரவாது — பூச்சியால் மட்டுமே பரவும். ஒருமுறை பாதிக்கப்பட்ட "
                "செடியைக் குணப்படுத்த முடியாது."
            ),
            "immediate_actions": [
                "பாதிக்கப்பட்ட செடிக்கு மருந்தில்லை — மற்றவற்றைக் காக்க அதை அகற்றி அழிக்கவும்.",
                "வெள்ளை ஈ வயலுக்குள் தப்பிச் செல்லாதவாறு செடிகளைப் பையில் போட்டு எடுத்துச் செல்லவும்.",
                "இலையின் அடிப்புறத்தில் சிறிய வெள்ளைப் பறக்கும் பூச்சிகள் உள்ளதா எனப் பாருங்கள்.",
                "வெள்ளை ஈயைக் கட்டுப்படுத்தவும் — அதுவே ஒரே பரவல் வழி.",
                "வயலைச் சுற்றியுள்ள களைகளை அகற்றவும்.",
            ],
            "prevention": [
                "நோய் எதிர்ப்பு அல்லது தாங்கும் திறன் கொண்ட ரகங்களைப் பயிரிடவும் — இதுவே மிகச் சிறந்த வழி.",
                "நடவுக்கு முன் பூச்சி புகாத வலைக்குள் நாற்று வளர்க்கவும்.",
                "வெள்ளை ஈயின் எண்ணிக்கையைக் கண்காணிக்கவும் குறைக்கவும் மஞ்சள் ஒட்டும் பொறிகளைப் பயன்படுத்தவும்.",
                "பாதிக்கப்பட்ட பழைய தக்காளிப் பயிருக்கு அருகில் புதிய பயிரை நடவேண்டாம்.",
            ],
            "expert_note": (
                "அடுத்த பருவத்திற்கான நோய் எதிர்ப்பு ரகங்கள் மற்றும் வெள்ளை ஈ "
                "மேலாண்மை குறித்து வேளாண் விரிவாக்க அலுவலரிடம் பேசுங்கள். "
                "நோயுற்ற செடிகளுக்கு மருந்து தெளிப்பதால் அல்ல, ரகத் தேர்வாலும் "
                "பூச்சிக் கட்டுப்பாட்டாலுமே இந்நோய் வெல்லப்படுகிறது."
            ),
        },
    },
    ("tomato", "mosaic_virus"): {
        "name": "Tomato Mosaic Virus",
        "severity": SEVERITY_HIGH,
        "en": {
            "summary": "A very persistent virus spread mainly by handling. Hygiene is everything.",
            "symptoms": (
                "Light and dark green mottling or mosaic patterning on the leaves. Leaves "
                "may be narrow, fern-like or distorted. Plants are stunted, and fruit can "
                "ripen unevenly with internal browning."
            ),
            "cause": (
                "An extremely stable virus spread mostly by hands, clothing, tools and "
                "contaminated seed — not by insects. It can survive in dry plant debris and "
                "on surfaces for a long time, and tobacco products can carry it."
            ),
            "immediate_actions": [
                "Remove and destroy infected plants; there is no cure.",
                "Wash hands thoroughly with soap before and after handling tomato plants.",
                "Disinfect all tools, stakes and trays.",
                "Do not use tobacco products while working with the crop, and wash hands if you do.",
                "Work with healthy plants first, infected ones last.",
            ],
            "prevention": [
                "Use certified virus-free seed and resistant varieties.",
                "Keep strict hand and tool hygiene throughout the season.",
                "Destroy all crop debris; the virus survives in dry material.",
                "Do not save seed from an infected crop.",
            ],
            "expert_note": (
                "Contact your agricultural extension officer to confirm the diagnosis — "
                "mosaic symptoms can be confused with herbicide damage and nutrient "
                "deficiency, and the correct response is completely different."
            ),
        },
        "ta": {
            "summary": "கையாள்வதால் பரவும் மிக நிலைத்த வைரஸ். தூய்மையே முக்கியம்.",
            "symptoms": (
                "இலைகளில் வெளிர் மற்றும் அடர் பச்சை நிறக் கலவை அல்லது மொசைக் "
                "வடிவம். இலைகள் குறுகியதாகவோ, சிலம்பு போன்றோ, சிதைந்தோ இருக்கும். "
                "செடிகள் குள்ளமாகும்; காய்கள் சீரற்ற முறையில் பழுத்து உள்ளே "
                "பழுப்பு நிறமாகலாம்."
            ),
            "cause": (
                "கைகள், உடைகள், கருவிகள், மாசுபட்ட விதை வழியாகப் பரவும் மிக நிலையான "
                "வைரஸ் — பூச்சிகளால் அல்ல. உலர்ந்த பயிர்க் கழிவுகளிலும் "
                "மேற்பரப்புகளிலும் நீண்ட காலம் உயிர் வாழும்; புகையிலைப் "
                "பொருட்களும் இதைச் சுமக்கும்."
            ),
            "immediate_actions": [
                "பாதிக்கப்பட்ட செடிகளை அகற்றி அழிக்கவும்; மருந்து எதுவும் இல்லை.",
                "தக்காளிச் செடிகளைக் கையாளும் முன்பும் பின்பும் சோப்பு போட்டு கைகளை நன்கு கழுவவும்.",
                "அனைத்துக் கருவிகள், கழிகள், தட்டுகளைக் கிருமி நீக்கம் செய்யவும்.",
                "பயிருடன் வேலை செய்யும்போது புகையிலைப் பொருட்களைப் பயன்படுத்த வேண்டாம்; பயன்படுத்தினால் கைகளைக் கழுவவும்.",
                "முதலில் ஆரோக்கியமான செடிகளுடனும், கடைசியாகப் பாதிக்கப்பட்டவற்றுடனும் வேலை செய்யவும்.",
            ],
            "prevention": [
                "சான்றளிக்கப்பட்ட வைரஸ் இல்லாத விதைகளையும் நோய் எதிர்ப்பு ரகங்களையும் பயன்படுத்தவும்.",
                "பருவம் முழுவதும் கை மற்றும் கருவித் தூய்மையைக் கண்டிப்பாகக் கடைப்பிடிக்கவும்.",
                "அனைத்துப் பயிர்க் கழிவுகளையும் அழிக்கவும்; உலர்ந்த பொருளிலும் வைரஸ் உயிர் வாழும்.",
                "பாதிக்கப்பட்ட பயிரிலிருந்து விதை சேமிக்க வேண்டாம்.",
            ],
            "expert_note": (
                "நோயை உறுதிப்படுத்த வேளாண் விரிவாக்க அலுவலரைத் தொடர்பு கொள்ளவும் — "
                "மொசைக் அறிகுறிகளைக் களைக்கொல்லி பாதிப்பு மற்றும் ஊட்டச்சத்துக் "
                "குறைபாட்டுடன் குழப்பிக் கொள்ள வாய்ப்புள்ளது; அவற்றுக்கான தீர்வு "
                "முற்றிலும் வேறுபட்டது."
            ),
        },
    },
    ("corn", "gray_leaf_spot"): {
        "name": "Maize Gray Leaf Spot",
        "severity": SEVERITY_MODERATE,
        "en": {
            "summary": "Rectangular grey lesions bounded by the leaf veins.",
            "symptoms": (
                "Narrow, rectangular, grey to tan lesions that run parallel to the leaf "
                "veins and stop sharply at them, giving them a distinctly blocky look. They "
                "start on lower leaves and move up. Severe infection can weaken stalks and "
                "cause lodging."
            ),
            "cause": (
                "The fungus survives on maize residue left on the soil surface. High "
                "humidity, heavy dew and minimum-tillage fields with continuous maize favour "
                "it most."
            ),
            "immediate_actions": [
                "Assess how many leaves above the cob are affected — that is what drives yield loss.",
                "Avoid moving through the crop when leaves are wet.",
                "Plan residue management: bury or remove infected stubble after harvest.",
            ],
            "prevention": [
                "Grow resistant hybrids, the most reliable control.",
                "Rotate out of maize for at least one season.",
                "Do not leave maize residue on the surface in a continuous maize field.",
                "Avoid excessively dense planting.",
            ],
            "expert_note": (
                "If lesions reach the leaves above the cob before grain fill, consult your "
                "agricultural officer about approved fungicides and the right timing."
            ),
        },
        "ta": {
            "summary": "இலை நரம்புகளால் எல்லைப்படுத்தப்பட்ட செவ்வக வடிவ சாம்பல் நிறப் புண்கள்.",
            "symptoms": (
                "இலை நரம்புகளுக்கு இணையாக ஓடி, அவற்றில் திடீரென நின்றுவிடும் "
                "குறுகிய, செவ்வக வடிவ, சாம்பல் முதல் மண் நிறப் புண்கள்; இதனால் "
                "அவை தனித்துவமான கட்டை வடிவில் தெரியும். கீழ் இலைகளில் தொடங்கி "
                "மேல்நோக்கி நகரும். கடுமையான தாக்குதல் தண்டுகளை பலவீனப்படுத்தி "
                "செடி சாய்வதற்கு வழிவகுக்கும்."
            ),
            "cause": (
                "மண் மேற்பரப்பில் விடப்படும் சோளக் கழிவுகளில் இப்பூஞ்சை உயிர் "
                "வாழ்கிறது. அதிக ஈரப்பதம், கனத்த பனி, குறைந்த உழவுடன் தொடர்ச்சியாக "
                "சோளம் பயிரிடப்படும் வயல்கள் இதற்கு மிக உகந்தவை."
            ),
            "immediate_actions": [
                "கதிருக்கு மேல் எத்தனை இலைகள் பாதிக்கப்பட்டுள்ளன எனப் பாருங்கள் — மகசூல் இழப்பை அதுவே தீர்மானிக்கிறது.",
                "இலைகள் ஈரமாக இருக்கும்போது பயிரினூடே நடமாடுவதைத் தவிர்க்கவும்.",
                "கழிவு மேலாண்மைக்குத் திட்டமிடவும்: அறுவடைக்குப் பிறகு பாதிக்கப்பட்ட தாள்களைப் புதைக்கவும் அல்லது அகற்றவும்.",
            ],
            "prevention": [
                "நோய் எதிர்ப்பு ஒட்டு ரகங்களைப் பயிரிடவும் — இதுவே மிக நம்பகமான கட்டுப்பாடு.",
                "குறைந்தது ஒரு பருவமாவது சோளத்திலிருந்து மாறிப் பயிர் சுழற்சி செய்யவும்.",
                "தொடர்ச்சியான சோள வயலில் கழிவுகளை மேற்பரப்பில் விடவேண்டாம்.",
                "மிக அடர்த்தியான விதைப்பைத் தவிர்க்கவும்.",
            ],
            "expert_note": (
                "தானியம் நிரம்பும் முன்பே கதிருக்கு மேல் உள்ள இலைகளுக்குப் புண்கள் "
                "பரவினால், அனுமதிக்கப்பட்ட பூஞ்சைக் கொல்லிகள் மற்றும் சரியான "
                "நேரம் குறித்து வேளாண் அலுவலரை அணுகவும்."
            ),
        },
    },
}

# "healthy" is a valid model output and needs its own encouraging message.
HEALTHY_CONTENT = {
    "en": {
        "summary": "No disease symptoms were detected in this image.",
        "symptoms": (
            "The leaf in this image looks healthy — no lesions, spots, mould or "
            "discolouration were detected."
        ),
        "cause": "",
        "immediate_actions": [
            "Keep checking the crop every few days, especially after rain or humid weather.",
            "Look closely at the older, lower leaves — most diseases start there.",
            "Photograph and report anything new as soon as you notice it.",
        ],
        "prevention": [
            "Water at the base of the plant rather than over the leaves.",
            "Keep enough space between plants for air to move.",
            "Clear crop debris, which is where most diseases survive between seasons.",
            "Practise crop rotation.",
        ],
        "expert_note": (
            "Remember that one photograph shows only one leaf. If the plant looks unwell "
            "overall, photograph a different part of it, or ask an agricultural expert."
        ),
    },
    "ta": {
        "summary": "இந்தப் படத்தில் நோய் அறிகுறிகள் எதுவும் கண்டறியப்படவில்லை.",
        "symptoms": (
            "இந்தப் படத்தில் உள்ள இலை ஆரோக்கியமாகத் தெரிகிறது — புண்கள், புள்ளிகள், "
            "பூஞ்சை அல்லது நிற மாற்றம் எதுவும் கண்டறியப்படவில்லை."
        ),
        "cause": "",
        "immediate_actions": [
            "சில நாட்களுக்கு ஒருமுறை பயிரைச் சரிபார்க்கவும், குறிப்பாக மழை அல்லது ஈரமான காலநிலைக்குப் பிறகு.",
            "பழைய கீழ் இலைகளை உன்னிப்பாகப் பாருங்கள் — பெரும்பாலான நோய்கள் அங்கேயே தொடங்கும்.",
            "புதிதாக ஏதேனும் தெரிந்தால் உடனே படமெடுத்துத் தெரிவிக்கவும்.",
        ],
        "prevention": [
            "இலைகள் மீது அல்லாமல் செடியின் அடிப்பகுதியில் நீர் பாய்ச்சவும்.",
            "காற்று செல்ல செடிகளுக்கு இடையே போதிய இடைவெளி விடவும்.",
            "பயிர்க் கழிவுகளை அகற்றவும் — பருவங்களுக்கு இடையே பெரும்பாலான நோய்கள் அங்கேயே உயிர் வாழ்கின்றன.",
            "பயிர் சுழற்சியைக் கடைப்பிடிக்கவும்.",
        ],
        "expert_note": (
            "ஒரு புகைப்படம் ஒரு இலையை மட்டுமே காட்டுகிறது என்பதை நினைவில் கொள்ளுங்கள். "
            "செடி ஒட்டுமொத்தமாக நலிவாகத் தெரிந்தால், வேறு பகுதியைப் படமெடுக்கவும், "
            "அல்லது வேளாண் நிபுணரை அணுகவும்."
        ),
    },
}

HEALTHY_CROPS = ["tomato", "potato", "corn", "rice"]

# Shown when the model predicts something we have no verified entry for.
NO_TREATMENT_TEXT = {
    "en": (
        "No verified recommendation is currently available for this result. "
        "Please consult a qualified agricultural expert or your local "
        "agricultural extension officer."
    ),
    "ta": (
        "இந்த முடிவுக்கு தற்போது சரிபார்க்கப்பட்ட பரிந்துரை எதுவும் இல்லை. "
        "தயவுசெய்து தகுதிவாய்ந்த வேளாண் நிபுணரையோ உங்கள் பகுதி வேளாண் "
        "விரிவாக்க அலுவலரையோ அணுகவும்."
    ),
}
